spryk: template
description: "Adds a new *module*MapperInterface to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    domainEntity:
        inherit: true

    tableName:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Persistence/Mapper/ZedPersistenceMapper.php.twig

    targetFilename:
        value: "{{ module }}Mapper.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Mapper"

preSpryks:
    - ZedPersistenceMapperInterface
